examples/index.rs, examples/load.rs, src/bin/electrs.rs, src/config.rs, src/daemon.rs
I tested this locally and seems to work ok. I wanted to check if there was interest and if there's a preference on how to go about it.
This PR is meant to add configurability for the tcp listening port (default to 50001 for mainnet) and for the bitcoin rpc ip:port.
It attempts to avoid repeating the default ports around the code and it defaults to correct ports for mainnet/testnet - i.e. the configurability is meant to be optional.
I'll make updates to the PR based on feedback/interest, results of additional testing, etc
=> make electrs listen port and bitcoin rpc url configurable

doc/usage.md, src/daemon.rs
Not sure if this was intentional, if so please close this PR.
If it wasn't intentional this removes size_on_disk as a field in the BlockchainInfo struct since it is not used anywhere. As per usage.md changes, this does affect logging - since it only affects bitcoind logging it may be ok as user can still log getblockchaininfo via bitcoin-cli.
=> remove unused size_on_disk

examples/compact.rs, src/bin/electrs.rs, src/config.rs, src/store.rs
This should allow initial indexing on Raspberry Pi: #38
=> Support initial indexing on low-memory devices using --jsonrpc-import flag

examples/txid_collisions.rs, src/store.rs
Also, add `DBStore::iter_scan()` for efficient scanning of large amount of rows.
=> Add simple transaction ID prefix collision length calculator

doc/usage.md
I thought it would be helpful to share the config I'm using for an SSL endpoint with electrs. I had some trouble setting up hitch and I already had NGINX installed so I tried setting it up and it's been working like a charm the past few weeks. I've had no problem pointing electrum clients to port 50002.
=> Add NGINX SSL sample config

src/daemon.rs, src/query.rs
Query bitcoind for the list of txids in the block instead of fetching the whole block, deserializing it and re-computing them.
=> Improve query.get_merkle_proof() performance

src/rpc.rs
Bug found in review of #105 
https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-transaction-id-from-pos
=> tx_id -> tx_hash in transaction.id_from_pos

src/config.rs
This allows hostname to be passed, rather than only IP addresses.
My use case for this is having the bitcoin node running on a separate docker instance. The name of the other docker instance resolves to its docker network IP.
=> Resolve hostname for arguments passing an address

doc/usage.md
If I don't set a `electrum-rpc-addr` flag, by default electrs only listens for tcp6 connections. In order to accept tcp4, I need to add `--electrum-rpc-addr="127.0.0.1:50001`.
This is not a big deal since setting the flag fixes it, but adding this info to the docs should make it easier for users.
Also, the `config.rs` file should be changed since the help for this option lists `127.0.0.1:50001` as the default, which is not correct (at least on my install).
I also added a sample unit file for systemd.
=> Documentation Updates

doc/usage.md
Since Eclair Mobile now has a full feature set, there's been some extra interest in electrs since Eclair allows user-elected electrum servers.
I've had a few people reach out to me on Twitter confused as to why their Eclair Mobile won't connect to their Electrs. The reason (which isn't clear from the Eclair menu) is that Eclair denies self-signed SSL certs. So I added a section to the electrs docs on how to install certbot to get free SSL certs and modified your nginx template to use certbot certs.
Electrs is great, and it's been perfect for the new Eclair Mobile I've been using.
=> Update docs for use with Eclair Mobile

doc/usage.md
This updates the minimum version for Rust from 1.28 to the current latest which is 1.33. This is because 1.28 may fail on build due to #129.
It also updates the minimum version of Electrum to the current latest of 3.3 since version 3.2 is officially unsupported due to a known phishing vulnerability.
=> Update min versions for installation

src/errors.rs
Just fixing a typo I noticed in the log output.
=> Fix interrupt typo

src/index.rs
This makes electrs_index_height report the right height after
`invalidateblock` call in bitcoind
=> [stats] Update index height when chain shortens

src/app.rs, src/fake.rs, src/index.rs, src/mempool.rs, src/store.rs
There were several places where `Vec<Row>` was created just to iterate
it later and throw away, thus allocating memory unnecessarily. This
translates those `Vec`s to `Iterator`s in order to improve the
efficiency.
**Note** I didin't test this yet as my node is syncing, but the changes were pretty straightforward.
=> Bunch of Vec<Row> translated to Iterator<Item=Row>

examples/index.rs, src/bin/electrs.rs, src/cache.rs, src/config.rs, src/daemon.rs, src/lib.rs
On cache hit, this improves performance of `blockchain.transaction.get_merkle` and thus wallet synchronization
=> Add cache for block transaction IDs

Cargo.lock, Cargo.toml, RELEASE-NOTES.md, build.rs, config_spec.toml, doc/usage.md, src/config.rs, src/lib.rs
Since use of configuration files is both more secure and more
convenient and clap doesn't support config files, this switches to
configure_me, which supports config files, env vars and also generating
man pages.
Closes #151
This is WIP, I just wanted to show what I have before I go AFK for several hours. I tested it only very lightly. This also includes man page generation. :)
=> Use configure_me instead of clap

Cargo.lock, Cargo.toml, config_spec.toml, src/lib.rs
This commit upgrades `configure_me` and adds support for `--conf` and
`--conf-dir` parameters, which load the configuration from the specified
place.
=> Support for user-specified onfiguration files/dirs

RELEASE-NOTES.md, config_spec.toml, src/bin/electrs.rs, src/cache.rs, src/config.rs, src/query.rs
Also, move TransactionCache into `cache` module.
Following #161 by @dagurval.
=> Add byte-size limit to transaction & block txids' caches

Cargo.lock, Cargo.toml, build.rs
* This should resolve #180, not sure (couldn't get past rocksdb on 1.34)
* Uses new, cleaner way of specifying `config_spec.toml`
FYI, if you `cargo install cfg_me`, you can see the man page easily by running `cfg_me man` in electrs source tree. You can store it with `cfg_me -o electrs.1 man` :)
=> Update `configure_me` as well as other packages

src/cache.rs, src/metrics.rs
During development of #195 it was a bit confusing that memory usage reported to prometheus sometimes jumped. This was most likely due to new transactions being stored in cache. Adding this metric helps understand how memory is being used by electrs.
=> Report cache usage metrics to prometheus

config_spec.toml
After a recent switch to configure_me in ec049b9a, the 'mainnet'
arg value became 'bitcoin'. 2c50791d then updated db dir location
but the doc for the --network arg remained stale.
An alternative is to accept both 'mainnet' and 'bitcoin' but
it would be confusing IMHO.
=> Correct --network arg values in the doc

src/rpc.rs
**Important: untested suggestion of how to solve the problem!**
This change implements non-blocking cleanup of threads. It achieves it
by cleaning up periodically based on thread ID, that gets sent from dead
thread over a channel. Aside from internal locks in the channel, there
are no other locks. The cleanup also happens only after a new connection
is accepted, but hopefully won't be an issue, unless there are many
connections that die and then nothing connects for a long time. A final
cleanup happens when the thread is finishing.
=> Actually wait for threads in RPC.

Cargo.lock, Cargo.toml, src/app.rs, src/bulk.rs, src/cache.rs, src/daemon.rs, src/index.rs, src/mempool.rs, src/notify.rs, src/query.rs, src/rpc.rs, src/util.rs
After my work on new bitcoin crate hash type system last year <https://github.com/rust-bitcoin/rust-bitcoin/pull/349> I find many project depending on the upstream `bitcoin` crate being unable to update to the latest version without spending a lot of effort on type replacements (plus some additional code editing in cases like merklization). Due to my work on adding support to Signet (which was implemented in rust-bitcoin fork containing the new type system) I had to do this work, so I propose it for your consideration as a PR here. Pls review it before significant changes to the master, since it will take many hours of my time again to do any rebase, which I do not have.
New hash type system from bitcoin crate does not cover all cases for merkle values; and the same function may be …
=> Migration to new bitcoin hash type system; bumping to the latest rust-bitcoin release

doc/usage.md
This change makes many improvements to the documentation aimed at higher clarity and robustness. Aside from rewording and reordering various parts, it makes sure the documentation is up to date with the reality and best (security and cleanness) practices.
The list of changes:
* Changes the title of "Installation" section to make it clear it's manual and from source
* Points at more convenient options right on top
* Adds "Build dependencies" subtitle
* Makes "Build" a subtitle as it belongs under "Manual installation from source" section
* Recommends using Debain native packaging, which is more secure than `rustup`
* Suggests installation and use of `cfg_me`
* Moves Docker-based installation higher to be better visible
* Informs that native, stable packages are not available yet.
* Adds …
=> Make documentation more clear, add recommendations

config_spec.toml, examples/index.rs, src/bin/electrs.rs, src/config.rs, src/daemon.rs
I used the quite convenient `-blocksdir` option (https://github.com/bitcoin/bitcoin/pull/12653) on my `bitcoind`, but had to fall back to symlinking the `blocks/` to be able to use Electrs with `blk`s on a different disk.
This makes Electrs aware that the `blk`s might not always be in `<config_dir>/blocks/`.
=> Add a `blocks_dir` option analogous to bitcoind's `-blocksdir`

Dockerfile
Recently when running `docker build`, I encountered a cryptic error during `electrs` compilation (something having to do with `src/bulk.rs`) that I eventually figured out had to do with file permissions. This might be because I run with `umask 077` on my host, or it might be due to some kind of host/container uid mismatch (though my host's uid is 1000...). 
Anyway, this cautionary `chown` has fixed the build for me.
=> docker: account for host/container permission differences

src/query.rs, src/rpc.rs
This adds a new RPC method that enables users to fetch the block hash
for given txid. It can thus be used to emulate `txindex=1` as explained
in the related issue.
Closes #287
=> Add blockchain.transaction.get_confirmed_blockhash

Cargo.toml
This makes the compression algorithms optional, but on by default to
keep the behavior. While one might think this just decreases the size a
bit, it has another advantage: when linking with system library it's not
needed to specify the paths of all these libraries because they are already
compiled in the system library.
Note: I have WIP update of the docs that will explain how to link to system
libraries, including with cross-compiling, I'm just waiting for some backport in
`bindgen`.
=> Make rocksdb compression algos optional

Cargo.lock
These new versions contain backports of fixes that make dynamic linking
less painful and cross compilation possible.
(I have a WIP doc update which I'm going to test now to see if the instructions work and then I'll file a PR.)
=> Updated librocksdb-sys and bindgen

doc/usage.md
**Important:** Instructions in this update depend on #325 being merged!
* The mentioned Debian repository is now considered beta, make the
wording much less scary.
* Documented how to link rocksdb dynamically and what are the pros/cons
* Documented how to cross compile
* Added `--locked` parameter to `cargo build` to prevent `cargo` from
updating lock file
* Use `./target/release/electrs` instead of `cargo run` to avoid
rebuilding footguns
* Added a link to in-depth explanation of cookie security
=> Updated documentation

Dockerfile
The check is based on the presence and responsiveness of the monitoring port 4224.
=> Add simple health check to Dockerfile.

Cargo.lock, Cargo.toml
The older version of `prometheus` depended on an old version of `spin`
which had a vulnerability related to locking. The new version of
prometheus doesn't use `spin` anymore so that the vulnerability is
fixed. Note that the vulnerability was unlikely on `x86_64` machines but
likely on ARM. `electrs` seems to be quite popular on various SBCs such
as Raspberry Pi, so fixing this is important.
More information: https://rustsec.org/advisories/RUSTSEC-2019-0013
Thankfully, `electrs` compiles with new `prometheus` without changes
despite it being semver breaking.
As you may have figured out, I ran `cargo audit` and it found one more vulnerability that to my knowledge is unrelated to `electrs` and a few smaller issues which I will sort out in a different PR (#335).
@romanz I'd strongly recommend …
=> Update prometheus to 0.10

.github/workflows/rust.yml, Dockerfile
This prevents `cargo` from changing the dependencies during build.
Closes #329
=> Run `cargo install` with  `--locked` in `Dockerfile`

Cargo.lock, Cargo.toml, src/config.rs, src/index.rs, src/query.rs
According to `cargo audit` crates `rust-crypto`, `dirs` and `failure`
are unmaintained/deprecated. This change replaces former two.
Unfortunately `failure` can't be replaced because it's a transitive
dependency of `rocksdb`, which is pinned. Fortunately it's in build
script only, which should have no noticable effect on the quality of
`electrs` itself.
As a nice side effect this should remove a bunch of useless code since
we pull only specifically `sha2` without bundling other cryptography.
=> Replace unmaintained crates with alternatives

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/build_problem.md, .github/ISSUE_TEMPLATE/config_problem.md, .github/ISSUE_TEMPLATE/feature_request.md
This adds four GitHub issue templates with these properties:
* Nudge people to read the docs
* Nudge inexperienced people to use automation
* Nudge people to provide important information (env, logs...)
* Assign myself (Kixunil) in case of build and config issues
=> Added issue templates

.dockerignore, .github/workflows/rust.yml, .gitignore, Dockerfile, tests/run.sh
https://github.com/romanz/electrs/runs/1492953787:
```
Run docker run -v $PWD/contrib/:/contrib -v $PWD/tests/:/tests --rm electrs:tests bash /tests/run.sh
Starting Bitcoin Core version v21.99.0-4165780c7...
Creating Electrum 4.0.5 wallet...
Generated 110 regtest blocks (33.167 kB) to bcrt1qgaddyzpdljaa7ry7cjh4en740c03ewgkjwgfh2
Started "electrs 0.9.0" with 110 blocks indexed
{"auto_connect":false,"blockchain_height":110,"connected":true,"default_wallet":"/root/.electrum/regtest/wallets/default_wallet","fee_per_kb":180000,"path":"/root/.electrum/regtest","server":"localhost","server_height":110,"spv_nodes":1,"version":"4.0.5"}
Loading Electrum wallet...
Running integration tests:
* getbalance
* getunusedaddress
* payto & broadcast
* get_tx_status
* getaddresshistory
* getbalance …
```
=> Add integration tests to CI

Cargo.lock, Cargo.toml, internal/config_specification.toml, src/config.rs
This is dependent on #238 and #240 and includes commit history from them (w/o this it would not build). Once these PRs will be merged I will rebase on master and clear the history so this PR can be reviewed (it has quite a few changes).
The only relevant commit in the history to Signet support is <https://github.com/romanz/electrs/commit/1a4fc7851ccb276614798c296339cd98e14bfa3a>
=> Support for Signet

doc/usage.md, internal/config_specification.toml, src/config.rs
This adds `auth` option and deprecates `cookie` which has a confusing
name. It's effectively renaming but we pretend it is not to avoid people
blindly changing the name without second thought.
Closes #349 (a new tracking issue will be created)
This is WIP because I intend to update the doc too but not before #359 is merged.
=> Implemented auth option and deprecated cookie

doc/cookie_deprecation.md, doc/usage.md
This adds more informtion about cookie deprecation, especially
motivation, so the users won't be frustrated because of unexplained
change. It also removes a warning that's no longer applicable.
=> Added in-depth explanation of cookie deprecation

internal/config_specification.toml, src/daemon.rs, src/index.rs, src/mempool.rs
Also use non-batched RPCs, to lower bitcoind RAM usage.
Following https://github.com/romanz/electrs/issues/373.
=> Reduce the default `index_batch_size` to 10

src/mempool.rs
I wrote this in the github editor, so no promises that it compiles, but this should avoid several extra heap allocations and moves while fetching the mempool, and, more importantly, get electrs out of an infinite loop of fetching the full mempool forever when there exist RBF transactions.
=> Ignore individual mempool transaction fetch fails

src/config.rs
The warning was supposed to be shown when `cookie` is specified not the
other way around.
I have no clue how this slipped through, sorry. :(
=> Fixed inverted logic of deprecation

Dockerfile, doc/usage.md
This adds an Entrypoint to the Dockerfile and fixes #322.
It also introduces multistage Docker build, that reduces the image size from ~1.85GB to ~463MB, because the rust toolchain is no longer in the resulting image.
=> Optimize Dockerfile

Dockerfile, doc/usage.md
With my last PR #387 I messed up with filesystem permissions and health check. This is going to fix that. Besides this I removed the parameters from entrypoint, so they can be set via env variables. Also removed obsolete lines from Dockerfile and added another example for running the image.
=> Fix Dockerfile, add another example

src/daemon.rs, src/errors.rs, src/rpc.rs
Reply to malformed json-rpc requests with json-rpc responses containing a spec-compliant error code. For electrum-protocol-specific errors reply with an error code of 1 (`BAD_REQUEST`) or 2 (`DAEMON_ERROR`) depending on whether the error originated from the daemon or not.
**Edit:** This builds on the changes in #390, which was a fix for #313
=> Use more detailed error codes

Cargo.lock
The new version of sha2 replaces its dependency `cpuid-bool` with
`cpufeatures` because it was renamed and the previous one is
unmaintained.
=> Updated sha2

Cargo.lock
The previous version of `tiny_http` had a vulnerability that's probably
not relevant to `electrs` but better not risk it. It also avoids ugly
red error from `cargo audit`. :)
=> Updated tiny_http

doc/usage.md
Current `usage.md` contains only one example in `RPC examples` which uses `echo` and `netcat`. The PR adds new and corresponding example in `Python` which can speed up the initial use of the `electrs` for people who try to use the project for the first time.
=> Add python example in RPC examples

doc/usage.md
As suggested in comment https://github.com/romanz/electrs/pull/415#issuecomment-870345086 , `json.dumps` is added in-place of a manual construction of a request message into the Python example RPC examples
=> Added json.dumps to Python example RPC examples

contrib/addr.py
Tested in both regtest and (custom) signet .
=> Inside contrib/addr.py example, add regtest and signet networks

.github/workflows/rust.yml
This should make sure to catch compatibility mistakes in commits.
I used some nicer trick in the past but at first I'd like to see if this helps at all.
=> Set toolchain in GitHub actions to 1.41.1

src/config.rs
Current verbosity level of master are the ones here: https://docs.rs/stderrlog/0.5.1/src/stderrlog/lib.rs.html#377
p2p branch uses different level values for verbosity d153bfa2eb4435fbe2f70d38ece76152c0bcff66. This surprised me when testing outpoint notification in p2p branch (the trace logs fill my disk storage completely after two days of usage).
This PR restores the same old levels in p2p branch as master.
=> Use the same log verbosity levels as master

Dockerfile, src/config.rs
Otherwise, clippy fails with:
```
warning: identical conversion
--> /media/roman/3TB/roman/Code/electrs/target/debug/build/electrs-56b1e395b2bcf88c/out/configure_me_config.rs:339:25
|
339 |                 db_dir: db_dir.into(),
|                         ^^^^^^^^^^^^^ help: consider removing `.into()`: `db_dir`
|
= note: `#[warn(clippy::identity_conversion)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_conversion
warning: identical conversion
--> /media/roman/3TB/roman/Code/electrs/target/debug/build/electrs-56b1e395b2bcf88c/out/configure_me_config.rs:340:29
|
340 |                 daemon_dir: daemon_dir.into(),
|                             ^^^^^^^^^^^^^^^^^ help: consider removing `.into()`: `daemon_dir`
|
= …
```
=> Disable 'clippy::identity_conversion' on generated configuration module + add clippy to CI

Cargo.lock, Cargo.toml
It should allow dynamic linking on Debian 11 (https://packages.debian.org/bullseye/librocksdb-dev) and on Ubuntu 21.04 (https://packages.ubuntu.com/hirsute/librocksdb-dev).
=> Downgrade librocksdb-sys to 6.11.4

Cargo.toml
It would be useful to detect old DBs:
https://github.com/romanz/electrs/pull/477#discussion_r707600255
RocksDB compilation time increases 1m03s -> 1m07s (+6%).
Total electrs build time is 2m05s.
=> Add snappy to RocksDB features

.github/workflows/rust.yml, Dockerfile
Use debug build for build/clippy/fmt/unittests (using https://github.com/actions-rs).
Use release build for integration tests (using Docker).
=> Split CI into build and integration jobs

contrib/history.py, src/electrum.rs, src/status.rs, src/tracker.rs
No need to use transaction cache for getting output values.
=> Simplify 'blockchain.scripthash.get_balance' implementation 

RELEASE-NOTES.md, doc/usage.md
This should hopefully make the major changes more visible and avoid
surprises.
Assumes #477 will get merged (in other words, don't merge before it)
Since this changes formatting & release notes significantly it felt more appropriate to open a separate PR.
I'm also thinking usage.md is quite large now, maybe split it up?
=> Improve documentation of 0.8.x -> 0.9.0 upgrade

RELEASE-NOTES.md, src/bin/electrs.rs, src/electrum.rs, src/index.rs, src/lib.rs, src/server.rs, src/signals.rs, src/tracker.rs
It should allow resuming initial sync (fixing #494).
Also, refactor `index_batch_size` usage.
=> Close index DB if interrupted during initial sync

RELEASE-NOTES.md, doc/usage.md
Some people still incorrectly use trace log level and get burned by this update.
=> Warn about log level

src/index.rs, src/p2p.rs
We already assume that blocks are processed in ascending order.
=> Use blocks' height iterator (instead of a map)

RELEASE-NOTES.md, src/config.rs
Should fix https://github.com/romanz/electrs/issues/355#issuecomment-926903119.
It still can be set using:
```
RUST_LOG=electrs=TRACE target/release/electrs <args>
```
See https://docs.rs/env_logger for more usage examples.
=> Disable setting TRACE verbosity by '-vvvv'

RELEASE-NOTES.md, doc/usage.md
This warns users that they shouldn't touch `db_dir` internals except for
deleting the old `mainnet` database. It explains in details how to do
upgrade and deleting properly, calls it out in release notes and fixes
small style mistake in nearby heading.
It can be thought of as more explicit/detailed version of
8b8ebea0018d3e9a97ce965845b1914df4b4d8a4 or a textual alternative to
PR #513.
=> Detailed documentation of db_dir

Cargo.lock, Cargo.toml, RELEASE-NOTES.md
https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md
=> Release 0.9.0

doc/usage.md
With new `rocksdb` it's no longer necessary to disable features when dynamically linking.
Thus this change removes instructions to add `--no-default-features`.
However there's now a new feature called `metrics` which enables Prometheus.
This change also documents this and explains how to turn it off.
Closes #517
=> Update documentation regarding cargo features

src/index.rs
Otherwise, it will be 0 until the a new block is indexed.
Following https://github.com/romanz/electrs/issues/505#issuecomment-930651597.
=> Initialize chain height metric

doc/usage.md
Removing/renaming unsupported switches was not called out explicitly and it's possible that someone is using a different bitcoind address, not just port.
Closes #520
=> Clarify upgrading to 0.9.0

src/server.rs
Otherwise, the server fails to send RPC result to the client:
https://github.com/romanz/electrs/issues/508#issuecomment-928254892
The bug can be reproduced on testnet using:
```python
$ cat test.py 
import socket
import sys
import time
s = socket.create_connection(('localhost', 60001))
s.sendall(b'{"jsonrpc": "2.0", "method": "blockchain.scripthash.subscribe", "params": ["93df2ed6d3031610206a9ef6ee5d7c2bc538d6689ffb5ce964144b2b90bdc9e1"], "id": 1}\n')
s.shutdown(socket.SHUT_WR)  # the server should stop "receiver loop" now, but not drop the connection
time.sleep(1)
print(s.recv(1000))
```
The server fails to send the response:
```
[2021-09-30T17:51:14.361Z ERROR electrs::server] 0: disconnecting due to failed to send response: "{\"id\":1,\"jsonrpc\":\"2.0\",\"result\":\"f7dd2df65f0eb38f413 …
```
=> Don't shutdown write-side before all responses are sent back

src/electrum.rs
Tested locally (with a warm cache) using `netcat 127.0.0.1 50001 < all12_subs.txt`:
```
$ RUST_LOG=electrs=info,electrs::server=debug ./server.sh bitcoin 2>&1 | cut -c -80
...
[2021-10-29T07:51:44.068Z DEBUG electrs::server] 0: connected
[2021-10-29T07:51:44.112Z DEBUG electrs::server] 0: recv [{"jsonrpc":"2.0","meth
[2021-10-29T07:51:44.112Z DEBUG electrs::server] 0: recv [{"jsonrpc":"2.0","meth
[2021-10-29T07:51:51.768Z DEBUG electrs::server] 0: send [{"id":"m/0/0","jsonrpc
[2021-10-29T07:51:52.370Z DEBUG electrs::server] 0: send [{"id":"m/1/0","jsonrpc
[2021-10-29T07:51:58.962Z DEBUG electrs::server] 0: disconnected
```
[all12_subs.txt](https://github.com/romanz/electrs/files/7439930/all12_subs.txt)
```
$ curl -s localhost:4224 | grep blockchain.scripthash …
```
=> Allow multiple scripthashes' subscription in parallel

internal/config_specification.toml, src/config.rs
This pull request adds a possiblity to print out the current program version and exit immediately.
There are cases where I need to grab versions of multiple apps on my system. It would be great if I could get electrs version without parsing its logs (`Starting electrs 0.9.2 on x86_64 linux with Config { network: Bitcoin...`).
This is for example also handy when I update nix packages on my `nix-bitcoin` node and I need to recheck the program versions before actually switching to them (`nixos-rebuild switch`).
=> Add possibility to print out the program version without actually running it

RELEASE-NOTES.md, doc/upgrading.md, internal/config_specification.toml, src/config.rs
Please use `RUST_LOG` to specify logging verbosity.
See https://github.com/env-logger-rs/env_logger/ for details.
=> Remove `verbose` configuration

.github/dependabot.yml
Merging this opens update PRs like they can be seen here https://github.com/dbast/electrs/pulls
Proposed updates can be merged if CI is green or closed to be ignored.
There are also commands to tell dependabot e.g. to ignore specific major versions `@dependabot ignore this major version` as described in the PRs.
=> Add dependabot config for autmatic cargo update PRs

Dockerfile
Note: I've decided to not add a default health check to the Dockerfile, since the monitoring port is different for each network. I could add a default for mainnet, but then by default testnet and signet installations would be unhealthy.
If you want to add a health check to your docker-compose.yaml, you can use:
```
healthcheck:
test: ["CMD-SHELL", "curl -fSs http://localhost:4224/ || exit 1"]
```
=> Dockerfile: re-add curl, so it can be used for docker health checks

src/server.rs, src/thread.rs
Usecase: I was changing my client & server configuration around a lot (trying raw Bitcoin Core, turning on/off Tor etc) and ended up trying to connect with SSL activated on the client but without running Electrs behind Nginx. Naturally it failed, but to save my future self or the next person some time, I suggest adding a clear warning in the log.
Feel free to tidy up the change or instruct me in how to best improve it. My Rust-fu is weak.
=> Warn on attempt to connect over SSL

README.md
I think we wanted to add this but forgot. Used the word "altcoin" instead of "shitcoin" to avoid "x is not a shitcoin but an altcoin" arguments.
=> Clearly state that altcoins are not supported.

doc/upgrading.md
The free space required peaks higher than the final size before and during compaction.
Final size is ~40G, peak was ~60G on my machine.
=> More accurate free space required for reindexing

Cargo.lock, Cargo.toml, internal/config_specification.toml, src/config.rs
This removes the feature for skipping default config files and replaces
it with a configure_me implementation.
Closes #217
~~Note: `cfg_me` supporting this will be released soon.~~ Done.
Sorry for this taking so long time.
=> Use configure_me to skip default config files

doc/install.md
Current docs lacks instruction to install electrs and librocksdb for other releases of Ubuntu and Debian which includes LTS versions so adding it.
cc @romanz
=> Add guide for other Ubuntu & Debian releases to compile and install librocksdb

Cargo.lock, Cargo.toml, src/chain.rs, src/electrum.rs, src/mempool.rs, src/p2p.rs, src/status.rs, src/types.rs
Known benefits of the upgrade:
* Removed dependencies on a bunch of useless RNGs since `rand` was
upgraded in `bitcoin`
* Clearer code - `BlockHash::all_zeros()`
Related change: manual construction of genesis block changed to use
function from `bitcoin` crate.
The resulting binary is 50+kB smaller on my machine (release build).
=> Upgrade `bitcoin` to 0.29.1

internal/config_specification.toml, src/config.rs, src/daemon.rs, src/p2p.rs
This PR attempts to solve the issue raised in #418 
It is pretty straightforward, a `signet_magic` can be added as an option. If it is not set the magic is the default value for the network (`network.magic()`).
It is not fully operational though, I tried to run it against a custom signet and it seems that it downloads some blocks then fails for some reason. Here's the full log of a typical run:
```
Starting electrs 0.9.8 on x86_64 linux with Config { network: Signet, db_path: "/home/electrs/db/signet", daemon_dir: "/data/signet", daemon_auth: CookieFile("/data/signet/.cookie"), daemon_rpc_addr: 192.168.240.3:38332, daemon_p2p_addr: 192.168.240.3:38333, electrum_rpc_addr: 127.0.0.1:60601, monitoring_addr: 127.0.0.1:34224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, …
```
=> WIP: Feature/custom signet

internal/config_specification.toml, src/config.rs
This is a follow-up on #762, to allow the `signet-magic` option to be passed as the hex string that is found in Bitcoin Core logs.
Previously the magic was passed directly as a u32, which was cumbersome as user had to manually reverse the bytes in the magic given by Core and convert it to an int.
With this PR, you can grep `magic` in Bitcoin Core logs (let's say it's `deadbeef`), and then directly pass it as argument `--signet-magic deadbeef`. Previously you would have to first figure out that it corresponds to `4022250974`.
I should have directly made it like that sorry.
=> Takes signet magic in hex as in bitcoin core logs

.cargo/audit.toml
Following https://github.com/romanz/electrs/pull/775
=> RUSTSEC-2020-0159 is no longer an issue

doc/install.md
Cross compilation instructions contained `gcc` dependency two times, but it should certainly be `gcc` and `g++` instead.
=> fix redundancy or copy & paste typo

doc/install.md
Added instructions how to cross-compile for a different architecture and OS version (Debian based) than the target system.
=> cross-compilation instructions using debootstrap

doc/config.md
People seeing Nginx config may falsely assume electrs uses HTTP but it's not the case. Putting heads up about this may avoid future confusion.
Closes #813
=> Clarify that electrs doesn't use HTTP

.github/workflows/rust.yml
=> Disable cargo-bloat action

src/electrum.rs
Add [blockchain.transaction.id_from_pos](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-transaction-id-from-pos) protocol method.
Fixes #834.
=> Implement `blockchain.transaction.id_from_pos` RPC

src/config.rs, src/p2p.rs
This is a follow-up of #768 
Since then rust-bitcoin has merged a [PR](https://github.com/rust-bitcoin/rust-bitcoin/pull/1288) that creates a new `Magic` type and modifies the api.
This PR is only a WIP/placeholder while the change is not tagged in a version of rust-bitcoin, its scope is only the necessary changes to make it work with the new way rust-bitcoin handles network's magic.
=> WIP upgrade with Magic type

internal/config_specification.toml
Just a simple typo fix I came across while playing around with custom signet.
This typo shows up when calling `electrs --help` with the following error:
```
--monitoring-addr         Prometheus monitoring 'addr:port' to listen on
(default: 127.0.0.1:4224 for mainnet,
127.0.0.1:14224 for testnet, 127.0.0.1:24224
for regtest and 127.0.0.1:34224 for regtest)
```
It should have read `127.0.0.1:34224 for signet`.
=> Fix typo in config_specification.toml

src/mempool.rs, src/tracker.rs
Otherwise, electrs cannot be gracefully stopped during the first mempool sync (currently [having >100k transactions](https://mempool.space/)).
=> Allow existing mempool sync on SIGINT

Cargo.lock, Cargo.toml
Following https://github.com/serde-rs/serde/issues/2538.
=> Avoid precompiled 'serde_derive' >=1.0.172

Cargo.lock, Cargo.toml, src/daemon.rs, src/index.rs, src/p2p.rs, src/status.rs, src/tracker.rs, src/types.rs
This is a proof of concept using bitcoin_slices since it seems a good fit.
Parsing a block with rust_bitcoin is expensive because of allocating all the needed data, since many times you are interested only in a subset of it, we can skip most of the work, for example, to find a transaction.
UPDATED: added visiting of inputs and outputs via bitcoin_slices since the idea seems interesting for the maintainer
Fixes #864.
=> Bitcoin slices integration

examples/tx_collisions.rs
```
$ time cargo run --release --example tx_collisions db/bitcoin
Finished release [optimized] target(s) in 0.05s
Running `target/release/examples/tx_collisions db/bitcoin`
prefix=4ee974b6585fb468 heights: 91722 91880
prefix=220fe15429d88599 heights: 91812 91842
real	2m37.073s
user	2m34.878s
sys	0m3.164s
```
=> Add txid collision scanner

src/bin/electrs.rs
It's a leftover from https://github.com/rust-lang-deprecated/error-chain
=> Drop 'recursion_limit' definition

src/tracker.rs
Should resolve the ordering issue (returning the first matching tx), as well as not parsing the next blocks.
=> Return first txid-matching transaction

Cargo.lock, Cargo.toml, internal/config_specification.toml, src/cache.rs, src/chain.rs, src/config.rs, src/p2p.rs, src/status.rs
This is not a merge candidate.
Upgrade dependencies required to use the recently released `rust-bitcoin v0.31.0-rc1` release.
Done while trying to upgrade `bdk` to use the bitcoin RC release.
=> Upgrade `bitcoin` dependency to 0.31.0

internal/config_specification.toml, src/config.rs, src/db.rs, src/tracker.rs
Following https://github.com/romanz/electrs/issues/680#issuecomment-1824841535.
=> Allow setting RocksDB log directory

doc/config.md
The `--skip-default-conf-files` flag is often desired but people may miss it because it's not in the doc, so this documents it.
Further, to avoid problems with people missing flags this adds a recommendation to run `electrs --help` so if we ever forget to update the doc people will learn about the new arguments anyway.
Fixes #962.
=> Improve config documentation

src/mempool.rs
Extracted from https://github.com/romanz/electrs/pull/970. This PR is a prereq of #970.
`FeeHistogram` was being recomputed from scratch on every call to `Mempool::sync`. This was unnecessary. Instead we can mutate the existing histogram bin state once on each new transaction added to or removed from the mempool.
Prometheus mempool metrics are only updated once per bin at the end of every sync.
=> avoid redundant recomputation of fee histogram bins

src/mempool.rs
Following #971.
CC: @conduition
=> Remove Mempool::new and Mempool::empty

src/daemon.rs, src/mempool.rs
This PR improves initial mempool sync significantly.
Before the change (efa045c):
```
$ RUST_LOG=electrs::mempool=DEBUG ./server.sh bitcoin
...
[2023-12-20T19:14:25.916Z DEBUG electrs::mempool] loading 13693 mempool transactions
[2023-12-20T19:15:33.444Z DEBUG electrs::mempool] 13693 mempool txs: 13693 added, 0 removed
```
After the change (ab12ce7):
```
$ RUST_LOG=electrs::mempool=DEBUG ./server.sh bitcoin
...
[2023-12-20T19:25:50.766Z DEBUG electrs::mempool] loading 13693 mempool transactions
[2023-12-20T19:25:57.931Z DEBUG electrs::mempool] 13693 mempool txs: 13693 added, 0 removed
```
=> Use batched RPC to fetch mempool entries & transactions

src/daemon.rs, src/mempool.rs
Otherwise, RBF may cause current sync implementation to fail.
=> Don't fail mempool sync on missing transactions

doc/install.md
Fixes: https://github.com/romanz/electrs/issues/1001
---
Do you prefer for it to be documented in the dynamic linking section or move it to be more globally after this line 
https://github.com/romanz/electrs/blob/576b5b2bb642df786e17d2a58429d32fae482841/doc/install.md?plain=1#L185
?
=> Document cleanse of build artifacts

Cargo.lock, Cargo.toml, src/daemon.rs, src/index.rs, src/p2p.rs, src/types.rs
=> Bump 'bitcoin' dependency to 0.32.0

examples/tx_collisions.rs, src/config.rs, src/mempool.rs, src/merkle.rs
`Transaction::txid()` was deprecated in the update to 0.32 (just renamed)
=> fix deprecation and clippy warnings

src/chain.rs, src/db.rs, src/index.rs, src/types.rs
In the WriteBatch struct, I changed the `Vec<Box<[u8]>>` fields to `Vec<[u8, N]>`, which saves on memory allocations when indexing blocks and putting the results of that in the db, before this pr that adds up to 1 per unique output address per block (funding), 1 per spent utxo per block (spending) and 1 per transaction (txid) (and a bit more for tip_row and header_rows).
~When retrieving from the db currently `Box`es are still used, but this can be fixed by using rocksdb's raw iterators. (The optimizer might be able to even remove the `Box`es now that they are directly dropped, but as with almost all optimizations, they are not guaranteed).~
I also managed to fix this, 800000+ less `Box`es are now made when retrieving the headers on startup, and a lot too on electrum protocol requests (i …
=> Save on allocations by using fixed size types for database rows

src/config.rs
closes #1044 
Feel free to edit any of the messages by directly committing (but review is still fine)
Is `std::process::exit(1);` desirable? This forces users to remove the flag with a nice message, in future releases they will get an error from the arg parser. When not exiting people might (and will) miss it, how many people look at the logs when booting a program? (thinking about one-click install full node distros for example)
=> deprecate unused config option `timestamp`

Dockerfile
Switch from lower case "as" to upper case "AS" to be consistent with the other keywords.
fixes #1085
=> fix inconsistent casing

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, src/signals.rs
Satisfies #709, utilizing ctrlc in place of signal hook on Windows only.
=> Implement ctrlc in place of signal hook on Windows

src/index.rs
If the index is on a SSD, sync perfomance should improve.
When the blocks' data is stored on a HDD, it takes ~3h to finish the initial sync (without full compactions, which take an additional ~1h):
Most of the time is spent waiting for p2p messages (i.e. bitcoind reading blocks from the spinning disk):
Writing the index is done in parallel with the reading:
=> Separate reading & writing into scoped threads

src/cache.rs, src/electrum.rs, src/status.rs
After filtering, we need the serialized bytes for caching only.
=> Don't deserialize transactions if not needed

src/electrum.rs, src/tracker.rs
Simplify [`bsl::FindTransaction`](https://github.com/RCasatta/bitcoin_slices/blob/b3f6af9dbae96f0f95fb5cd3a448d19453b4beec/src/bsl/block.rs#L82) to return the serialized transaction.
=> Don't deserialize transaction bytes in `blockchain.transaction.get` RPC

.github/workflows/rust.yml
=> Run CI only on 'master' branch and PRs

src/status.rs
Also, refactor `Unspent` balance a bit.
=> Document `status.rs`

Cargo.lock, Cargo.toml
According to benchmark block parsing is up to 30% faster
https://github.com/RCasatta/bitcoin_slices/pull/44
=> bump bitcoin slices dep 0.9.2 -> 0.10.0

src/mempool.rs, src/status.rs, src/types.rs
Hi! I updated multiple outdated `electrumx-spesmilo` documentation links in `mempool.rs`, `status.rs`, and `types.rs`, replacing them with the correct `electrum-protocol` equivalents.
- **Replaced:** `electrumx-spesmilo.readthedocs.io` links with `electrum-protocol.readthedocs.io`
- **Files updated:**
- `src/mempool.rs`
- `src/status.rs`
- `src/types.rs`
=> fix: dead links in Rust source files

doc/upgrading.md
Arammatical mistake in the *Upgrading checklist* section:  
- **Before:** *Make sure you upgrade at time when you don't need to use electrs for a while.*  
- **After:** *Make sure you upgrade at a time when you don't need to use electrs for a while.*  
Added the missing article *a* to make the sentence grammatically correct.
=> docs: fixed grammar in upgrading checklist

.github/workflows/rust.yml
Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected
=> ci: bump actions/checkout to v4

doc/upgrading.md
Replaced the outdated reference to docker.md with the correct link to the Docker installation section in install.md within the upgrading guide. This ensures users are directed to the proper instructions for Docker-based installation and configuration.
=> Fix broken Docker installation link in upgrading guide

tests/run.sh
The line
```
set +eo pipefail
```
was misspelled: Bash doesn't understand such a fused syntax.
The correct way to disable both modes is separately:
```
set +e — disables script termination on error (enabled by default via set -e).
set +o pipefail — disables script termination on pipe error (enabled by default via set -o pipefail).
```
Why is this important?
Strict mode is enabled at the beginning of the script:
```
set -euo pipefail
```
This means that the script will terminate immediately in case of any error.
But cleanup must correctly terminate all background processes, even if something has already gone wrong (for example, one of the processes has already been terminated and the kill command will generate an error).
If you leave it in strict mode, cleanup may abort on the first error …
=> fix(run.sh): correct syntax for disabling strict mode in cleanup function

Cargo.lock, Dockerfile.ci
```
warning: package `cargo_toml v0.15.0` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked
```
https://crates.io/crates/cargo_toml/0.15.3 requires Rust 1.64, so let's downgrade to https://crates.io/crates/cargo_toml/0.14.1.
=> Update `cargo_toml` dependency and fix Dockerfile warning

Cargo.lock, Cargo.toml
I set it to 1.0.184 in Cargo.toml for the same reason it got done [here](https://github.com/RustCrypto/RSA/pull/360), Cargo will pull in the latest version actually (the now latest version 1.0.219 is semver-compatible with 1.0.184).
Serde's changelog mentions mostly bug fixes and binary size improvements, I only noticed a slight improvement in binary size (after this PR 99.97% of the size of before).
=> Update `serde` to the latest version after the precompiled library got removed

src/daemon.rs
The comment incorrectly referenced a non-existent function. The timeout
actually controls RPC call duration, while new block waiting is handled
via new_block_rx channel in server.rs.
=> fix: outdated comment jsonrpc_timeout is for RPC calls, not wait_for_new_block
