romanz/electrs

src/config.rs, src/daemon.rs
This PR builds on top of https://github.com/romanz/electrs/pull/19 and adds regtest support
=> Add Regtest mode

.travis.yml
Hopefully fixes https://github.com/romanz/electrs/issues/33 and ok as a workaround
=> fix travis out of memory issue

examples/index.rs, examples/load.rs, src/bin/electrs.rs, src/config.rs, src/daemon.rs, src/errors.rs
Daemon RPCs will block until re-connected successfully (following #18).
=> Handle JSONRPC disconnections gracefully

doc/usage.md
=> Update instructions with low RAM arguments

Cargo.lock, Cargo.toml, src/app.rs, src/bin/electrs.rs, src/bulk.rs, src/config.rs, src/daemon.rs, src/errors.rs, src/fake.rs, src/index.rs, src/lib.rs, src/mempool.rs, src/metrics.rs, src/notify.rs, src/query.rs, src/rpc.rs, src/signal.rs, src/store.rs, src/util.rs
Should build on beta/nightly Rust.
=> Support Rust 2018 edition

src/mempool.rs
Fixes issue where old mempool entires were only removed if new ones were
also added.
Diff is best viewed ignoring whitespace (add [`?w=1`](https://github.com/romanz/electrs/pull/127/files?w=1))
=> [mempool] Fix bug on removing entries

src/bulk.rs, src/index.rs, src/util.rs
=> Allow "chain-trimming" reorgs and add some tests

src/daemon.rs
This change switches from `Mutex<u64>` to `AtomicU64`, which is faster
and somewhat more elegant to write. It keeps the `Counter` type for
backwards compatibility.
The downside is that it doesn't work on as many platforms and requires
fairly recent compiler.
=> Use atomic u64 instead of Mutex for counter

doc/usage.md
=> Add documentation for running Tor service

src/bin/electrs.rs, src/bulk.rs
=> Allow stopping bulk indexing via SIGINT/SIGTERM

doc/usage.md
=> docs: add hardware specs and explain storage usage

.circleci/config.yml, Cargo.lock, Cargo.toml, RELEASE-NOTES.md, doc/usage.md, src/app.rs, src/config.rs, src/daemon.rs, src/index.rs, src/lib.rs, src/mempool.rs, src/query.rs, src/store.rs, src/util.rs
Following #140 & Debian buster supporting 1.34 :)
=> Support Rust >=1.34

Cargo.lock, Cargo.toml, build.rs
This update fixes the issue with hypens and additionally makes error
messages from the build script nicer.
Fixes #170
=> Updated to `configure_me` 0.3.5

Cargo.toml
Update rust-bitcoin & bitcoin_hashes #181
=> Update rust-bitcoin & bitcoin_hashes

doc/usage.md
I think that this information being visibly documented could save people a long debugging session or sad compile time.
See #226
=> Added a note about broken toolchains on RPi4

src/rpc.rs
Otherwise, multiple connections will "overwrite" each other subscriptions.
=> Update # of subscriptions correctly

src/mempool.rs, src/query.rs, src/rpc.rs
Following https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain.scripthash.get_mempool
Otherwise, the client will disconnect:
https://github.com/spesmilo/electrum/issues/6289
=> Return fee for unconfirmed transactions history

src/rpc.rs
When `Message::Done` was received before the cleanup loop executed it
led to a deadlock since the loop didn't see the receiving end being
disconnected and it also had strong reference via `Arc` preventing it
from dropping.
This change solves the problem by splitting the channel and only keeping
the sender in `Connection`. The reciver is passed to `handle_replies` as
an extra argument, making sure it will be used exactly once.
The main advantage of this method over trying to keep the receiver
inside `Connection` is that it hanles cases when the thread panicks and
possibly forgetting explicit close in future refactors. Another
advantage is being able to remove one `Arc::clone` and I have an idea
for removing locking on `senders` in the future too.
Closes #283
**Not tested yet**, however, …
=> Drop receiver in handle_replies

doc/usage.md
=> Update rpc example following protocol changes

.dockerignore, Cargo.lock, Dockerfile, contrib/get_tip.py, electrs_index/Cargo.toml, electrs_index/src/config.rs, electrs_query/Cargo.toml, electrs_rpc/Cargo.toml, tests/run.sh
```
$ docker build . --rm -t electrs:tests
$ docker run -v $PWD/tests/:/tests -it --rm electrs:tests bash /tests/run.sh
Starting bitcoind...
Creating electrum wallet...
{
"msg": "Please keep your seed in a safe place; if you lose it, you will not be able to restore your wallet.",
"path": "/build/electrs/data/electrum/wallet",
"seed": "put wealth income elephant wait rhythm blade dose narrow moral absorb lady"
}
Generating regtest coins...
{"chain":"regtest","blocks":110,"headers":110,"bestblockhash":"45afc44c18be8a8f0c802ce68ea4cbaef1cd0cd4ba5217f692ffd9bad52ec95e","difficulty":4.656542373906925e-10,"mediantime":1606680858,"verificationprogress":1,"initialblockdownload":false,"chainwork":"00000000000000000000000000000000000000000000000000000000000000de","size_on_disk":33167,"pruned":false, …
```
=> Add Docker-based integration tests

Dockerfile, tests/run.sh
Example build:
https://github.com/romanz/electrs/pull/353/checks?check_run_id=1621531548
=> Build latest Electrum in Dockerfile

doc/config_example.toml
=> Fix verbose parameter in config example

doc/usage.md
This improves documentation of configuration based on @BTCBellyButton
suggestions in #344. It contains a few more tweaks.
I have also added a few more line breaks to make editing easier (separate commit to simplify review).
=> Improve doc

internal/config_specification.toml
According to @craigraw this should help with performance issues while a
more complicated improvement is being developed.
See #382
=> Bumped default wait_duration_secs from 5 to 10

contrib/client.py, contrib/tx_fee.py, src/electrum.rs
Following #230 - please note that this PR is based over `p2p` branch (as described [here](https://github.com/romanz/electrs/issues/308#issuecomment-806061229)).
=> Add initial support for JSON-RPC batching

src/daemon.rs, src/electrum.rs, src/server.rs
See https://www.jsonrpc.org/specification#error_object
Fixes #413.
=> Use JSONRPC error codes

src/electrum.rs
=> Allow calling blockchain.scripthash.get_history without subscription

contrib/history.py, src/bin/query.rs, src/electrum.rs, src/lib.rs, src/status.rs, src/tracker.rs
=> Add blockchain.scripthash.get_balance RPC

src/daemon.rs, src/electrum.rs
Should fix https://github.com/romanz/electrs/issues/427
=> Return original JSON from getrawtransaction RPC

doc/usage.md, src/app.rs, src/cache.rs, src/config.rs, src/daemon.rs, src/index.rs, src/mempool.rs, src/metrics.rs, src/query.rs, src/rpc.rs
Fix a bunch of lints emtited by `cargo +nightly check`. This is my first PR to this repo, so this just does a few of the more basic ones. Specifically, this PR introduces no API changes to the `electrs` library.
Please review critically and if there is anything I can do to fit into the projects style better please say so now so I can save your time on following PRs.
Thanks,
Tobin.
=> Clippy +nightl fixes

doc/usage.md
=> p2p doc: in bitcoin.conf maxconnections should be >11, fixes #429

.github/workflows/rust.yml
https://github.com/actions-rs/toolchain#the-toolchain-file
=> Use rust-toolchain in GitHub actions

src/config.rs, src/daemon.rs
If not specified, use `--cookie-file`.
=> Fix `--auth` support

src/electrum.rs
=> Add server.features RPC

src/daemon.rs
See https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/190.
=> Add a workaround for latest Bitcoin Core

internal/config_specification.toml, src/config.rs, src/index.rs, src/status.rs, src/tracker.rs, tests/run.sh
=> Limit index lookups to prevent DoS for "popular" addresses

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/build_problem.md, .github/ISSUE_TEMPLATE/config_problem.md
These are mostly warnings about various things and asking additional information.
=> A bunch of improvements to issue templates

README.md
* Having usage up should make it more visible.
* Recommend people to use our guide as opposed to external guides which is kept up-to-date with the code.
=> Move usage in README up and recommend our guide

src/config.rs
Following https://github.com/romanz/electrs/issues/371#issuecomment-918217030
=> Fail if cookie is specified

contrib/history.py, src/electrum.rs, src/status.rs, src/tracker.rs
Also refactor 'blockchain.scripthash.get_balance'.
=> Implement 'blockchain.scripthash.listunspent' RPC

.github/workflows/rust.yml
=> Run 'cargo audit' in CI

internal/config_specification.toml, src/config.rs, src/daemon.rs
Following #495.
Also, fix https://github.com/romanz/electrs/issues/443.
=> Allow configuration of JSON-RPC timeout

doc/usage.md
https://github.com/romanz/electrs/issues/502
=> Add a release note about `db/mainnet` -> `db/bitcoin` rename

src/index.rs, src/metrics.rs
=> Add gauge metric to export latest block height

src/server.rs
It should be OK to retry in case of a RPC timeout.
Should help with https://github.com/romanz/electrs/issues/495.
=> Don't fail on HTTP timeouts from bitcoind RPC

doc/usage.md
=> Update build description for 32-bit OS

src/electrum.rs, src/status.rs, src/tracker.rs
Also, simplify the relevant code a bit.
=> Fix duplicate history computation

src/electrum.rs, src/index.rs, src/metrics.rs
=> Use correct Prometheus buckets for size and duration

src/daemon.rs, src/electrum.rs, src/p2p.rs, src/server.rs, src/status.rs
Fixes https://github.com/romanz/electrs/issues/522.
=> Use p2p protocol to replace `waitfornewblock` hidden RPC

src/bin/electrs.rs, src/daemon.rs, src/electrum.rs, src/index.rs, src/lib.rs, src/server.rs, src/signals.rs, tests/run.sh
=> Don't ignore signals during IBD

src/db.rs, src/index.rs
https://github.com/facebook/rocksdb/blob/d52b520d5168de6be5f1494b2035b61ff0958c11/include/rocksdb/db.h#L953
Note: `index_db_size` mertrics is removed.
=> Monitor various DB statistics via Prometheus

src/electrum.rs
https://github.com/romanz/electrs/issues/608#issuecomment-961778452
=> Don't warn when queried with unsubscribed scripthashes

doc/install.md, doc/usage.md
=> Add asciinema screencasts for quickstart installation and usage

src/electrum.rs, src/index.rs, src/server.rs, src/tracker.rs
Following https://github.com/romanz/electrs/issues/534#issuecomment-935982984.
It allows getting a `blockchain.headers.subscribe` notification each 2000 blocks:
```
$ echo '{"jsonrpc":"2.0","method":"blockchain.headers.subscribe","id":1}' | netcat localhost 60601 | ts
Oct 10 20:35:20 {"id":1,"jsonrpc":"2.0","result":{"height":2000,"hex":"00000020fcdd71929d32ac87147bd8e6e6006cc71d0ec860bfd742ebc0ff62692e020000a7b6887fb467fb44f06d8f316c854977ccfd5bea27e51269d9db4cdb62d9abc189d5535fae77031ed34e6200"}}
Oct 10 20:35:21 {"jsonrpc":"2.0","method":"blockchain.headers.subscribe","params":[{"height":4000,"hex":"00000020d963818f6259d0ca57992d2d086fc5cb12aafde003378178e4190d3573000000cd06b18141a6a81ef1b4f74e2e52d165e1a1137386e0aa0d4d94890c6d2c2bc7b8cc665fa72f011e4365d001"}]}
Oct 10 20:35:21 …
```
=> Support basic RPC handling during initial sync

src/cache.rs, src/index.rs, src/metrics.rs, src/p2p.rs, src/server.rs
This way we can see how much it took to receive specific p2p messages.
=> Improve p2p receiving metrics

README.md
This is quite important information that people occasionally miss. Documenting it visibly should help.
Additional context: https://github.com/romanz/electrs/issues/635#issuecomment-985402363
=> Clarify that electrs is intended for personal use

RELEASE-NOTES.md, internal/config_specification.toml
Following https://github.com/romanz/electrs/issues/635#issuecomment-985402363.
=> Disable `index_lookup_limit` by default

src/p2p.rs
Also, use a separate metrics for parsing duration monitoring.
=> Parse p2p messages in a separate thread

src/electrum.rs, src/tracker.rs
Otherwise, we may fail to retrieve existing transaction whose `txid[..8]` collides with other transactions.
=> Fix `txid` index collision handling

src/daemon.rs
https://github.com/romanz/electrs/pull/449 is no longer an issue :)
=> Use bitcoincore_rpc's getblockchaininfo implementation

.github/workflows/rust.yml
=> Install and run cargo-bloat in CI

.github/workflows/rust.yml
=> Add build matrix to test all features

src/electrum.rs
=> Don't log scripthash

src/mempool.rs
=> Fix mempool fee rate formatting

src/config.rs
Following https://github.com/romanz/electrs/pull/768/files#r968639660
=> Fixup signet magic error message

src/electrum.rs
=> Don't panic in case of an invalid block header height

Cargo.lock, Cargo.toml, RELEASE-NOTES.md
Following https://github.com/romanz/electrs/issues/783#issuecomment-1301932240
=> Bump version

Cargo.lock, Cargo.toml
Following https://github.com/romanz/rust-rocksdb/pull/1
=> Minor bump rocksdb

src/p2p.rs
Following https://github.com/rootzoll/raspiblitz/issues/3447
=> Improve error logging in case of p2p parsing error

doc/monitoring.md
=> Update prometheus instructions

src/electrum.rs
Fixes #812 
[Reference](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-scripthash-unsubscribe)
=> Add `blockchain.scripthash.unsubscribe` feature for RPC

CONTRIBUTING.md, README.md, contrib/testChanges.sh
=> Add script to test workflow actions locally

Cargo.lock, Cargo.toml
=> Bump `bitcoincore-rpc` dependency

Cargo.lock, Cargo.toml
Following https://github.com/romanz/electrs/security/dependabot/5
=> Update tempfile to 3.4.0

src/metrics.rs
Following https://github.com/romanz/electrs/issues/879#issuecomment-1555013078
=> Fixup error handling in Prometheus HTTP server

src/metrics.rs
=> Prefix Prometheus metrics with 'electrs_'

Dockerfile.ci
https://bitcoincore.org/en/2023/05/26/release-25.0/
=> Bump bitcoind used in CI

src/electrum.rs
=> Fix 'server.version' support for version range

Cargo.lock, Cargo.toml, RELEASE-NOTES.md
=> Bump version to 0.10.0-rc.1

src/daemon.rs
=> Less verbose logging when bitcoind is warming up

src/types.rs
This should save 2 reallocation for row since serialize will allocate without capacity (should be 4) and every time will double, so it will need other 2 re-allocation for a total of 3. While here is 1.
Do the same for HeaderRow.
=> Preallocate serialized vector of HashPrefixRow

src/index.rs
=> Remove IndexResult and index into db::WriteBatch

tests/run.sh
Fix https://github.com/romanz/electrs/actions/runs/5904335345/job/16016180838#step:4:75
=> Pass `--password=''` when invoking electrum CLI

src/index.rs
=> Optimize indexing via `bitcoin_slices`

tests/run.sh
Following https://github.com/spesmilo/electrum/commit/2e52b17a432bf5dacf28f4d5b3d8b8c9780f8c70
=> Fix electrum integration test script

Cargo.lock, Cargo.toml
=> Fix build failure on Raspberry Pi 4 (32bit)

src/mempool.rs
https://github.com/romanz/electrs/pull/917#pullrequestreview-1736677655
=> Fix log level during mempool sync interruption

src/db.rs, src/index.rs
=> Don't flush when nothing is written to DB

internal/config_specification.toml, src/config.rs, src/db.rs, src/tracker.rs
Following https://github.com/romanz/electrs/pull/959#discussion_r1405387423
=> Use Option<> for 'db_log_dir' config

Dockerfile.ci
https://bitcoincore.org/en/2023/12/06/release-26.0/
=> Bump bitcoind to 26.0

src/mempool.rs
The existing Mempool::sync logic maintained a mutable reference to the Mempool even though it's not actually using that mutable privilege for the majority of the time that the sync method is running. We separate the fetching the polling and applying processes, so that we can make mempool polling async.
=> Logically separate mempool sync polling and mutation

src/daemon.rs
=> Don't fail if bitcoind fee estimation is disabled

Dockerfile.ci
Following https://github.com/spesmilo/electrum/commit/581082d5bb678307ee05bf0616b1993d86a5ecb3.
=> Fix Electrum installation in Dockerfile.ci

Cargo.lock, Cargo.toml, src/p2p.rs, src/types.rs
Following https://github.com/rust-bitcoin/rust-bitcoin/pull/3509
=> Bump `bitcoin` to 0.32.4

internal/config_specification.toml, src/config.rs
Following https://github.com/rust-bitcoin/rust-bitcoin/pull/3453
=> Support testnet4

Cargo.toml, rust-toolchain.toml, src/config.rs, src/lib.rs
Also, fix a 'unused_imports' lint.
=> Fixup MSRV setting via `Cargo.toml`

README.md
fix 404 status URL in README.md
=> chore: fix 404 status URL in README.md

RELEASE-NOTES.md
=> docs: fix 404 status URL

src/chain.rs
Add missing semicolon for better code readability and consistency
=> Add missing semicolon in drop_last_headers function
